language: go
sudo: false

cache:
  directories:
    - $GOPATH/pkg/mod

git:
  depth: 1

env:
  - GO111MODULE=on

go:
  - 1.12.x

before_script:
  - go mod download 

script:
  - go test ./...  
  - go test -race ./...
