name: toxiproxy

type: go

up:
  - homebrew:
    - openssl
  - go:
      version: 1.12
      modules: true
      tools:
        - golang.org/x/tools/cmd/goimports

commands:
  build:
    run: go build ./...
    desc: 'build the project'
  test:
    run: go test ./...
    desc: 'run unit tests'
